#include <app_context.hpp>
#include <commands.hpp>
#include <argparse.h>

int main(int argc, char** argv)
{
    argparse::ArgumentParser program("rakpak");

    argparse::ArgumentParser cmd_new("new");
    cmd_new.add_description("Creates a new project based on selected template in your current working directory");

    argparse::ArgumentParser cmd_console("console");
    cmd_console.add_description("Executable project template with minimal boilerplate");
    cmd_console.add_argument("--name").help("Project name");

    argparse::ArgumentParser cmd_library("library");
    cmd_library.add_description("Library project template with minimal boilerplate");
    cmd_library.add_argument("--name").help("Project name");

    cmd_new.add_subparser(cmd_console);
    cmd_new.add_subparser(cmd_library);

    argparse::ArgumentParser cmd_build("build");
    cmd_build.add_description("Builds your project");
    cmd_build.add_argument("-p", "--profile").default_value("debug").help("Build profile");
    cmd_build.add_argument("-j", "--jobs").default_value(1).scan<'i', int>().nargs(1).help("Number of threads used for compiling");
    cmd_build.add_argument("-t", "--target").help("Build target for library projects");
    cmd_build.add_argument("-D", "--define").help("Add extra #define to build");
    cmd_build.add_argument("-l", "--log-level").default_value(1).scan<'i', int>().nargs(1).help("Sets the log level");
    cmd_build.add_argument("-f", "--log-file").help("Outputs logs to file path as well");

    argparse::ArgumentParser cmd_run("run");
    cmd_run.add_description("Builds and runs your project");
    cmd_run.add_argument("-p", "--profile").default_value("debug").help("Build profile");
    cmd_run.add_argument("-j", "--jobs").default_value(1).scan<'i', int>().nargs(1).help("Number of threads used for compiling");
    cmd_run.add_argument("-t", "--target").help("Sets build target for library projects");
    cmd_run.add_argument("-D", "--define").help("Add extra #define to build");
    cmd_run.add_argument("-l", "--log-level").default_value(1).scan<'i', int>().nargs(1).help("Sets the log level");
    cmd_run.add_argument("-f", "--log-file").help("Outputs logs to file path as well");

    argparse::ArgumentParser cmd_clean("clean");
    cmd_clean.add_description("Remove build output from the project directory");
    cmd_clean.add_argument("-r", "--recursive").nargs(0).help("Recursively clean subprojects as well");
    cmd_clean.add_argument("-P", "--purge").nargs(0).help("Remove build output and other files generated by rakpak");

    argparse::ArgumentParser cmd_install("install");
    cmd_install.add_description("Install project");
    cmd_install.add_argument("-s", "--scope").required().nargs(1).help("Install scope [local, user, system]");

    argparse::ArgumentParser cmd_export("export");
    cmd_export.add_description("Export various data about your project");
    cmd_export.add_argument("--pkg-config")
        .required()
        .nargs(0)
        .help("Export a pkg-config file for your project");

    program.add_subparser(cmd_new);
    program.add_subparser(cmd_build);
    program.add_subparser(cmd_run);
    program.add_subparser(cmd_clean);
    program.add_subparser(cmd_install);
    program.add_subparser(cmd_export);
    program.parse_args(argc, argv);
    rakpak::AppContext app_context;
    if (program.is_subcommand_used("new"))
    {
        if (cmd_new.is_subcommand_used("console"))
        {
            rakpak::cli::generate_from_template(app_context, "console");
        }
        else if (cmd_new.is_subcommand_used("library"))
        {
            rakpak::cli::generate_from_template(app_context, "library");
        }
    }
    else if (program.is_subcommand_used("build"))
    {
        if (cmd_build.is_used("log-level"))
            app_context.logger->log_level = 1 << cmd_build.get<int>("log-level");
        if (cmd_build.is_used("jobs"))
            app_context.build_options.jobs = cmd_build.get<int>("jobs");
        if (cmd_build.is_used("profile"))
            app_context.build_options.profile = cmd_build.get<std::string>("profile");
        rakpak::cli::build(app_context);
    }
    else if (program.is_subcommand_used("run"))
    {
        if (cmd_run.is_used("log-level"))
            app_context.logger->log_level = 1 << cmd_run.get<int>("log-level");
        if (cmd_run.is_used("jobs"))
            app_context.build_options.jobs = cmd_run.get<int>("jobs");
        if (cmd_run.is_used("profile"))
            app_context.build_options.profile = cmd_run.get<std::string>("profile");
        rakpak::cli::run(app_context);
    }
    else if (program.is_subcommand_used("clean"))
    {
        app_context.clean_options.recursive = cmd_clean.is_used("recursive");
        app_context.clean_options.purge = cmd_clean.is_used("purge");
        rakpak::cli::clean(app_context);
    }
    else if (program.is_subcommand_used("install"))
    {
        std::string install_scope = cmd_install.get<std::string>("scope");
        if (install_scope == "user")
            app_context.install_scope = rakpak::InstallScope::User;
        else if (install_scope == "system")
            app_context.install_scope = rakpak::InstallScope::System;
        else
            app_context.install_scope = rakpak::InstallScope::Local;
        rakpak::cli::install(app_context);
    }
    else if (program.is_subcommand_used("export"))
    {
        if (cmd_export.is_used("pkg-config"))
            rakpak::cli::generate_pkg_config(app_context);
    }
    return 0;
}